services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 80:80
        networks:
            - chess-network
        volumes:
            - ./frontend/src:/usr/share/nginx/html:ro
        depends_on:
            - backend

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - HTTP_HOST=127.0.0.1
            - HTTP_PORT=8080

            - DB_HOST=database
            - DB_PORT=5432
            - DB_DATABASE=chess_db
            - DB_USER=tsyden
            - DB_PASSWORD=chess
        networks:
            - chess-network
        volumes:
            - ./backend/src:/app
        depends_on:
            - database

    database:
        container_name: database
        image: postgres:16
        environment:
            - POSTGRES_DB=chess_db
            - POSTGRES_USER=tsyden
            - POSTGRES_PASSWORD=chess
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./database/migrations:/docker-entrypoint-initdb.d:ro
        networks:
            - chess-network

volumes:
    db_data:

networks:
    chess-network:
        driver: bridge
